#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDM_ABOUT                               104
#define IDI_PROTPURE                            107
#define IDC_PROTPURE                            109
#define IDF_COMPLEX                             113
#define IDF_DEFAULT                             115
#define IDF_EASY3                               117
#define IDF_EXAMPLE                             119
#define IDI_LOGO                                122
#define IDD_GET_MIXTURE                         123
#define IDD_GET_ENZYME                          126
#define IDD_STABILITY                           128
#define IDC_RUNNING                             130
#define IDD_PURIFICATION_HISTORY                132
#define IDD_NO_PROTEINS                         134
#define IDD_MIXTURE_ERROR                       135
#define IDD_ASKSAVE                             137
#define IDD_ASKABANDON                          138
#define IDD_AMMSULF                             140
#define IDD_ASRESULT                            142
#define IDD_OOPS                                144
#define IDD_STEPRECORD                          146
#define IDD_HEAT                                147
#define IDD_GELFILT                             149
#define IDD_POOL                                150
#define IDD_SELECTFRACTION                      151
#define IDD_SELECTFRACTIONS                     152
#define IDD_ASKABANDONSTEP                      153
#define IDD_IONEXCHANGE                         155
#define IDD_GETPH                               156
#define IDD_HIC                                 158
#define IDD_PRECIPITATE                         160
#define IDD_AFFINITY                            162
#define IDD_SORRY                               164
#define IDC_MESSAGE                             1000
#define IDC_RADIO1                              1000
#define IDC_SPIN1                               1000
#define IDC_STEPRECORD                          1000
#define IDC_LISTBOX                             1001
#define IDC_RADIO2                              1001
#define IDC_START                               1001
#define IDINFO                                  1001
#define IDC_ASMESSAGE                           1002
#define IDC_DEAE                                1002
#define IDC_PHENYL                              1002
#define IDC_VALUE2                              1002
#define IDADD                                   1003
#define IDC_G100                                1003
#define IDC_OCTYL                               1003
#define IDC_SPIN2                               1003
#define IDC_CMC                                 1004
#define IDC_END                                 1004
#define IDC_G50                                 1004
#define IDC_TEXT                                1004
#define IDC_S200                                1005
#define IDC_ACA54                               1006
#define IDC_QS                                  1006
#define IDC_ACA44                               1007
#define IDC_TRIS                                1007
#define IDC_ACA34                               1008
#define IDC_GLYCINE                             1008
#define IDC_SS                                  1008
#define IDC_INHIBITOR                           1009
#define IDC_P60                                 1009
#define IDC_SALT                                1009
#define IDC_IMIDAZOLE                           1010
#define IDC_P150                                1010
#define IDC_P300                                1011
#define IDC_PH                                  1012
#define IDC_MONOCLONAL1                         2000
#define IDC_MONOCLONAL2                         2002
#define IDC_MONOCLONAL3                         2003
#define IDC_POLYCLONAL                          2004
#define IDC_IMM_INHIBITOR                       2005
#define IDC_NICKEL                              2006
#define IDM_ABANDON_SCHEME                      40000
#define IDS_APP_TITLE                           40000
#define IDM_ABANDON_STEP                        40001
#define IDS_AUTHOR                              40001
#define IDM_START_FROM_STORED                   40002
#define IDS_ADDRESS1                            40002
#define IDM_STORE                               40003
#define IDS_ADDRESS2                            40003
#define IDM_HEAT                                40004
#define IDS_ADDRESS3                            40004
#define IDM_GEL_FILTRATION                      40005
#define IDS_TRANSLATOR1                         40005
#define IDM_ION_EXCHANGE                        40006
#define IDS_TRANSLATOR2                         40006
#define IDM_HYDROPHOBIC                         40007
#define IDS_TRANSLATOR3                         40007
#define IDM_AFFINITY                            40008
#define IDS_TRANSLATOR4                         40008
#define IDM_1D_PAGE                             40009
#define IDS_TRANSLATOR5                         40009
#define IDM_2D_PAGE                             40010
#define IDS_TRANSLATOR6                         40010
#define IDM_START                               40011
#define IDS_PROTEIN_D                           40011
#define IDM_COOMASSIE                           40012
#define IDS_RECORDTITLE                         40012
#define IDM_IMMUNOBLOT                          40013
#define IDS_METHOD                              40013
#define IDM_AMMONIUM_SULFATE                    40014
#define IDS_PROTEIN                             40014
#define IDM_HIDE_GEL                            40015
#define IDS_ENZYME                              40015
#define IDM_ASSAY                               40016
#define IDS_YIELD                               40016
#define IDM_DILUTE                              40017
#define IDS_ENRICHMENT                          40017
#define IDM_POOL                                40018
#define IDS_COST                                40018
#define IDM_INDEX                               40019
#define IDS_INITIAL                             40019
#define IDS_AMMONIUM_SULFATE                    40020
#define IDS_HEAT_TREATMENT                      40021
#define IDS_GEL_FILTRATION                      40022
#define IDS_ION_EXCHANGE                        40023
#define IDM_TUTORIAL                            40024
#define IDS_HYDROPHOBIC_INTERACTION             40024
#define IDS_AFFINITY_CHROMATOGRAPHY             40025
#define IDS_UNKNOWN                             40026
#define IDC_VALUE1                              40027
#define IDM_GO_HOME                             40027
#define IDS_FURTHER_RECORDS                     40027
#define IDS_MIXTURE_ERROR                       40028
#define IDS_LOST_ENZYME                         40029
#define IDS_NOT_FINISHED                        40030
#define IDS_TOO_COSTLY                          40031
#define IDS_STEPRECORDTITLE                     40032
#define IDS_STEPRECORD                          40033
#define IDS_HIDEGEL                             40034
#define IDS_HIDEBLOT                            40035
#define IDS_USING_ANTIBODY                      40036
#define IDS_2D_INITIAL                          40037
#define IDS_2D_POOLED                           40038
#define IDS_2D_FRACTION                         40039
#define IDS_INITIAL_MIXTURE                     40040
#define IDS_POOLED_FRACTIONS                    40041
#define IDS_SELECTED_FRACTION                   40042
#define IDS_SELECTED_FRACTIONS                  40043
#define IDS_FRACTIONS                           40044
#define IDS_SEPHADEX_G_50                       40045
#define IDS_SEPHADEX_G_100                      40046
#define IDS_SEPHACRYL_S_200_HR                  40047
#define IDS_ULTROGEL_ACA_54                     40048
#define IDS_ULTROGEL_ACA_44                     40049
#define IDS_ULTROGEL_ACA_34                     40050
#define IDS_BIO_GEL_P_60                        40051
#define IDS_BIO_GEL_P_150                       40052
#define IDS_BIO_GEL_P_300                       40053
#define IDS_ON                                  40054
#define IDS_ABSORBANCE_AT_280_NM                40055
#define IDS_FRACTION_NUMBER                     40056
#define IDS_ENZYME_LABEL                        40057
#define IDS_SALT_LABEL                          40058
#define IDS_PH_LABEL                            40059
#define IDS_AFFINITY_ELUTION_LABEL              40060
#define IDS_ADDED_ONE_FRACTION                  40061
#define IDS_ADDED_FRACTIONS                     40062
#define IDS_ION_EXCHANGE_CHROMATOGRAPHY         40063
#define IDS_DEAE_CELLULOSE                      40064
#define IDS_CM_CELLULOSE                        40065
#define IDS_Q_SEPHAROSE                         40066
#define IDS_S_SEPHAROSE                         40067
#define IDS_SALT_GRADIENT_TITLE                 40068
#define IDS_PH_GRADIENT_TITLE                   40069
#define IDS_START_OF_GRADIENT                   40070
#define IDS_END_OF_GRADIENT                     40071
#define IDS_PHENYL_SEPHAROSE                    40072
#define IDS_OCTYL_SEPHAROSE                     40073
#define IDS_PRECIPITATE_WARNING_1               40074
#define IDS_PRECIPITATE_WARNING_2               40075
#define IDS_HYDROPHOBIC_INTERACTION_CHROMATOGRAPHY 40076
#define IDS_IMMOBILIZED_A                       40077
#define IDS_IMMOBILIZED_B                       40078
#define IDS_IMMOBILIZED_C                       40079
#define IDS_POLYCLONAL                          40080
#define IDS_IMMOBILIZED_INHIBITOR               40081
#define IDS_NICKEL                              40082
#define IDS_TRIS                                40083
#define IDS_GLYCINE                             40084
#define IDS_INHIBITOR                           40085
#define IDS_IMIDAZOLE                           40086
#define IDS_HELPFILENAME                        40087
#define IDS_TUTORIAL_URL                        40088
#define IDS_SORRY                               40091
#define IDS_ERROR                               40093
#define IDS_NOTADMIN                            40095
